import streamlit as st
from topics import main as topics_main
from suggestions import main as suggestions_main
from engagement_analytics import main as engagement_main
from players import main as players_main
from rounds_game import main as rounds_main
from chat import main as chat_main
from streamlit_option_menu import option_menu
from feedback import main as feedback_main
from conversation import main as conversation_main

st.set_page_config(
    page_title="Social Media + AI Analytics Dashboard",
    page_icon="💡",
    layout="wide",
    initial_sidebar_state="expanded"
)
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)

selected = option_menu(
    menu_title=None,  # required
    options=["Home", "Engagement", "Players", "Topics", "Rounds", "T1: Suggestions", "T2: Chat", "T3: Feedback", "T4: Conversation"],  # required
    icons=["house", "bar-chart", "people", "bullseye", "lightbulb", "controller", "chat-dots", "pencil", "info-circle"],  # optional
    menu_icon="cast",  # optional
    default_index=0,  # optional
    orientation="horizontal",
    styles={
        "container": {
            "padding": "0!important", 
            "background-color": "black",
            "max-width": "95%",
            "margin": "0 auto"
        },
        "icon": {"color": "white", "font-size": "20px"},
        "nav-link": {
            "font-size": "12px",
            "text-align": "middle",
            "margin": "1px",
            "color": "white",
            "--hover-color": "#7A84C6",

        },
        "nav-link-selected": {
            "background-color": "#5438DC",
            "color": "white",
            "font-weight": "bold",
        }
    },
)

def landing_page():
    st.title("Social Media + AI Analytics Dashboard")
    
    st.markdown("""    
    __By Anders Giovanni Møller__

    This dashboard has a lot of numbers and plots to analyze the data from our experiment. Each tab will show something different. I'll do my best to explain at a high level what each tab is about.
                
    Below is a quick overview of each tab.
    
    ### 📊 Engagement Analytics
    Analyze overall engagement on a macro level - comparing control and treatment groups. It includes:
    - Comparative metrics between control and treatment groups - just some basic aggregate metrics.
    - Shannon entropy analysis for participation distribution. The idea here is to see if the treatment better allows for all people to engage in the game.
    - Engagement patterns over time - both per round but also in 2-minute buckets.
    - Comment length, sentiment, and toxicity analysis.
    - Distribution of reactions.
    
    ### 👥 Players Analysis
    Explore participants:
    - Initial survey responses.
    - Exit survey analysis.
    - Treatment effects.
    - Open-ended feedback analysis.
    
    ### 🎯 Topics Analysis
    Examine topic-specific engagement (cats, oats, Trump):
    - Topic-specific metrics: comments, likes, etc.
    - Use of AI treatment by topic.
    - Distribution of word counts by topic.
    - Distribution of reactions by topic.
    - Distribution of sentiment by topic.
                
    ### 🎮 Rounds Analysis
    Detailed analysis of individual games and rounds:
    - Timeline visualization of actions and comments.
    - Round-specific metrics
                
                
    ### 💡 Treatment 1: Suggestions
    Here we take a look at how the AI suggestions and how they were used:
    - Suggestion usage metrics
    - Distribution of comment length and sentiment of the suggestions compared to non AI-generated comments.
    - Use of AI-suggestions over time.
    - Distribution of reactions to AI-based comments compared to non AI-generated comments.
    - Analysis of reply patterns. How do people respond to comments generated by the AI compared to non AI-generated comments? What is the sentiment of the replies?
    - Reactions to the different types of suggestions.
                

    ### 💬 Treatment 2: Chat
    Here we look at how the users used the open chat feature. It is worth noting, that they max use per user per round is 8.
    
                
    ### 💬 Treatment 3: Feedback
    Here we look at how the users used the feedback feature.
                
    ### 💬 Treatment 4: Conversation
    Here we look at how the users used the conversation starter feature.
    """)


def main():

    if selected == "Home":
        landing_page()
    elif selected == "Engagement":
        engagement_main()
    elif selected == "Players":
        players_main()
    elif selected == "Topics":
        topics_main()
    elif selected == "Rounds":
        rounds_main()
    elif selected == "T1: Suggestions":
        suggestions_main()
    elif selected == "T2: Chat":
        chat_main()
    elif selected == "T3: Feedback":
        feedback_main()
    elif selected == "T4: Conversation":
        conversation_main()

if __name__ == "__main__":
    main()