import streamlit as st
import pandas as pd
import json
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from io import StringIO
from engagement_helpers.parsers import process_engagement_data
from treatments.parsers import (
    process_player_rounds, 
    match_selections_to_comments
)
from treatments.treatment_info import display_suggestions_metrics
from topics_helpers.metrics import display_suggestions_metrics_by_topic
from treatments.suggestions_visuals import (
    analyze_reply_patterns, 
    create_generation_length_comparison_plot, 
    create_generation_likes_distribution_plot, 
    create_generation_sentiment_plot, 
    create_generation_type_comparison_plot, 
    create_generation_reaction_distribution_plot,
    create_suggestion_usage_time_series
)
from rounds_game import load_data, process_game_data
from treatments.conversation_tree_for_regression import ConversationTree
import statsmodels.formula.api as smf
import statsmodels.api as sm
from typing import List

def main():
    """Main function to run the dashboard"""
    # Setup page
    
    df, df_round, df_batch = load_data()
    df_player_round = pd.read_csv('data/combining/combined/playerRound.csv')
    df, action_columns, comment_columns = process_game_data(df, df_round, df_batch)
    
    # Process data for both control and treatment groups
    processed_data, invalid_items = process_engagement_data(
        df,
        control_group='baseline_5'
    )

    player_round_data = process_player_rounds(processed_data, df_player_round)


    st.header("Treatment 1: Suggestions Analysis")
    st.markdown("""
    Here we will look at how the AI suggestions and how they were used. In the numbers and plots below, we distinguish between "generations" and "selections". A __generation__ is when a user is clicking on the button to have suggestions generated by the AI. A __selection__ is when a user clicks on a suggestion. Note: a user has the option to refresh generations 3 times per comment - each generation provides a _positive_, _neutral_ and _negative_ suggestion. For all plots below, __With Generation__ indicates that a comment is made with an AI-suggestion - we do string matching to match selected suggestion to the actual comments (a user could potentially change the selection). __Without Generation__ indicates that a comment is made without an AI-suggestion.
    """)

    detailed_data = display_suggestions_metrics(player_round_data)

    df_generations_matched = match_selections_to_comments(processed_data, detailed_data)

    topic_suggestions_metrics = display_suggestions_metrics_by_topic(df_generations_matched) # SHOULD BE USED IN SUGGESTIONS

    comment_length_plot = create_generation_length_comparison_plot(df_generations_matched)
    st.plotly_chart(comment_length_plot)

    like_type_plot = create_generation_likes_distribution_plot(df_generations_matched)
    st.plotly_chart(like_type_plot)

    st.divider()
    st.subheader("Use of AI-suggestions throughout the game")
    st.markdown("""
    The figures below show the total and average number of comments per round with and without AI-suggestions.
    """)

    generation_type_plot = create_generation_type_comparison_plot(df_generations_matched)
    st.plotly_chart(generation_type_plot)


    st.divider()
    st.subheader("Sentiment of comments with and without AI-suggestions")

    sentiment_plot, sentiment_data = create_generation_sentiment_plot(df_generations_matched)
    st.plotly_chart(sentiment_plot)

    st.divider()
    st.subheader("Reply patterns")
    st.markdown("""
    For the figures below, we look at all the replies to comments made with and without AI-suggestions. The replies can't be AI-generated, so we only look at natural human-made replies.
    """)

    reply_patterns_plot = analyze_reply_patterns(df_generations_matched)
    st.plotly_chart(reply_patterns_plot)


    st.divider()
    st.subheader("Reactions to comments made with AI-suggestions")
    st.markdown("""
    The figures below show the raw count and distribution of reactions to the different types of suggestions (positive, neutral, negative).
    """)
    reaction_distribution_plot, reaction_data = create_generation_reaction_distribution_plot(df_generations_matched)
    st.plotly_chart(reaction_distribution_plot)

    st.divider()
    st.subheader("Usage of AI-suggestions over time")
    st.markdown("""
    The figure below shows the time series of AI-suggestion usage.
    """)


    suggestion_usage_time_series_plot = create_suggestion_usage_time_series(df_generations_matched)
    st.plotly_chart(suggestion_usage_time_series_plot)


if __name__ == "__main__":
    main()